tags:
  - users
summary: updateUser()
description: Update a specific user
parameters:
  - name: id
    in: path
    required: true
    description:
      $ref: definitions/users.yaml#/definitions/Id/description
    schema:
      $ref: definitions/users.yaml#/definitions/Id
  - name: body
    in: body
    required: true
    description:
      $ref: definitions/users.yaml#/definitions/UpdateUser/description
    schema:
      $ref: definitions/users.yaml#/definitions/UpdateUser
  - name: accept-language
    in: header
    required: false
    description:
      $ref: definitions/common.yaml#/definitions/AcceptLanguage/description
    schema:
      $ref: definitions/common.yaml#/definitions/AcceptLanguage
responses:
  200:
    description: Message saying that the user is updated
    schema:
      $ref: definitions/common.yaml#/definitions/ErrorResponseMessage
  401:
    description: Unauthorized
    schema:
      $ref: definitions/common.yaml#/definitions/ErrorResponseMessage
  404:
    description: User not found
    schema:
      $ref: definitions/common.yaml#/definitions/ErrorResponseMessage
  500:
    description: System error
security:
  - api_key: []
