#####################################################
#                  DEFINITIONS                      #
#####################################################
definitions:
  Date:
    format: date
    type: string
  DateRegexYYYYMMDD: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$
  DateRegexYYYYMMDDHHMMSS: ((((19|20)([2468][048]|[13579][26]|0[48])|2000)-02-29|((19|20)[0-9]{2}-(0[4678]|1[02])-(0[1-9]|[12][0-9]|30)|(19|20)[0-9]{2}-(0[1359]|11)-(0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}-02-(0[1-9]|1[0-9]|2[0-8])))\s([01][0-9]|2[0-3]):([012345][0-9]):([012345][0-9]))
  Message:
    type: string
    description: Message
  WsVersion:
    type: string
    description: Specify if the service return a stub response or not
    enum:
      - STUB
      - LIVE

#####################################################
#                   OBJECTS                         #
#####################################################
  AcceptLanguage:
    type: string
    description: Accepts french or english
    pattern: (.+[;,])?fr-.*|(.+[;,])?en-.*
    default: fr-CA,fr;q=0.9

  ResponseMessage:
    type: object
    title: ResponseMessage
    required:
      - message
    properties:
      message:
        $ref: '#/definitions/Message'

  ErrorResponseMessage:
    type: object
    required:
      - message
    properties:
      message:
        $ref: '#/definitions/Message'
